//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimeJaNaiConverterGui.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnimeJaNaiConverterGui.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Model.
        /// </summary>
        public static string AddModelButtonText {
            get {
                return ResourceManager.GetString("AddModelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AllowOverwriteDescription {
            get {
                return ResourceManager.GetString("AllowOverwriteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Videos in Output Path to be Overwritten.
        /// </summary>
        public static string AllowOverwriteLabel {
            get {
                return ResourceManager.GetString("AllowOverwriteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Settings.
        /// </summary>
        public static string AppSettingsButtonText {
            get {
                return ResourceManager.GetString("AppSettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Settings.
        /// </summary>
        public static string AppSettingsHeader {
            get {
                return ResourceManager.GetString("AppSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AutoUpdateDescription {
            get {
                return ResourceManager.GetString("AutoUpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Update.
        /// </summary>
        public static string AutoUpdateLabel {
            get {
                return ResourceManager.GetString("AutoUpdateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Video Upscale.
        /// </summary>
        public static string BatchVideoUpscaleTabHeader {
            get {
                return ResourceManager.GetString("BatchVideoUpscaleTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        public static string ConsoleButtonText {
            get {
                return ResourceManager.GetString("ConsoleButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Version.
        /// </summary>
        public static string CurrentVersionLabel {
            get {
                return ResourceManager.GetString("CurrentVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EnableInterpolationDescription {
            get {
                return ResourceManager.GetString("EnableInterpolationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Interpolation.
        /// </summary>
        public static string EnableInterpolationLabel {
            get {
                return ResourceManager.GetString("EnableInterpolationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EnsembleDescription {
            get {
                return ResourceManager.GetString("EnsembleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensemble.
        /// </summary>
        public static string EnsembleLabel {
            get {
                return ResourceManager.GetString("EnsembleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Workflow.
        /// </summary>
        public static string ExportWorkflowButtonText {
            get {
                return ResourceManager.GetString("ExportWorkflowButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FfmpegOutputSettingsDescription {
            get {
                return ResourceManager.GetString("FfmpegOutputSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFmpeg Output Video Settings.
        /// </summary>
        public static string FfmpegOutputSettingsLabel {
            get {
                return ResourceManager.GetString("FfmpegOutputSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FfmpegPresetsDescription {
            get {
                return ResourceManager.GetString("FfmpegPresetsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFmpeg Presets.
        /// </summary>
        public static string FfmpegPresetsLabel {
            get {
                return ResourceManager.GetString("FfmpegPresetsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FinalResizeFactorDescription {
            get {
                return ResourceManager.GetString("FinalResizeFactorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Resize Factor.
        /// </summary>
        public static string FinalResizeFactorLabel {
            get {
                return ResourceManager.GetString("FinalResizeFactorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FinalResizeHeightDescription {
            get {
                return ResourceManager.GetString("FinalResizeHeightDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Resize Height.
        /// </summary>
        public static string FinalResizeHeightLabel {
            get {
                return ResourceManager.GetString("FinalResizeHeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Workflow.
        /// </summary>
        public static string ImportWorkflowButtonText {
            get {
                return ResourceManager.GetString("ImportWorkflowButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string InputFolderDescription {
            get {
                return ResourceManager.GetString("InputFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Folder.
        /// </summary>
        public static string InputFolderLabel {
            get {
                return ResourceManager.GetString("InputFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path of the video file to upscale..
        /// </summary>
        public static string InputVideoDescription {
            get {
                return ResourceManager.GetString("InputVideoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Video.
        /// </summary>
        public static string InputVideoLabel {
            get {
                return ResourceManager.GetString("InputVideoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string InterpolationFactorDescription {
            get {
                return ResourceManager.GetString("InterpolationFactorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolation Factor.
        /// </summary>
        public static string InterpolationFactorLabel {
            get {
                return ResourceManager.GetString("InterpolationFactorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string InterpolationModelDescription {
            get {
                return ResourceManager.GetString("InterpolationModelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string InterpolationModelLabel {
            get {
                return ResourceManager.GetString("InterpolationModelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolation Settings.
        /// </summary>
        public static string InterpolationSettingsHeader {
            get {
                return ResourceManager.GetString("InterpolationSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string ModelHeader {
            get {
                return ResourceManager.GetString("ModelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show More Upscale Settings.
        /// </summary>
        public static string MoreUpscaleSettingsLabel {
            get {
                return ResourceManager.GetString("MoreUpscaleSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OnnxModelPathDescription {
            get {
                return ResourceManager.GetString("OnnxModelPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONNX Model Path.
        /// </summary>
        public static string OnnxModelPathLabel {
            get {
                return ResourceManager.GetString("OnnxModelPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OutputFilenameDescription {
            get {
                return ResourceManager.GetString("OutputFilenameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Filename.
        /// </summary>
        public static string OutputFilenameLabel {
            get {
                return ResourceManager.GetString("OutputFilenameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path of the folder to upscale. The folder will be scanned and all video files (*.mkv, *.mp4, *.mpg, *.mpeg, *.avi, *.mov, *.wmv) found will be upscaled..
        /// </summary>
        public static string OutputFolderDescription {
            get {
                return ResourceManager.GetString("OutputFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Folder.
        /// </summary>
        public static string OutputFolderLabel {
            get {
                return ResourceManager.GetString("OutputFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Model.
        /// </summary>
        public static string RemoveModelButtonText {
            get {
                return ResourceManager.GetString("RemoveModelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Workflow.
        /// </summary>
        public static string ResetWorkflowButtonText {
            get {
                return ResourceManager.GetString("ResetWorkflowButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ResizeFactorBeforeUpscaleDescription {
            get {
                return ResourceManager.GetString("ResizeFactorBeforeUpscaleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize Factor Before Upscale.
        /// </summary>
        public static string ResizeFactorBeforeUpscaleLabel {
            get {
                return ResourceManager.GetString("ResizeFactorBeforeUpscaleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ResizeHeightBeforeUpscaleDescription {
            get {
                return ResourceManager.GetString("ResizeHeightBeforeUpscaleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize Height Before Upscale.
        /// </summary>
        public static string ResizeHeightBeforeUpscaleLabel {
            get {
                return ResourceManager.GetString("ResizeHeightBeforeUpscaleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string ReturnButtonText {
            get {
                return ResourceManager.GetString("ReturnButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SceneDetectionThresholdDescription {
            get {
                return ResourceManager.GetString("SceneDetectionThresholdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene Detection Threshold.
        /// </summary>
        public static string SceneDetectionThresholdLabel {
            get {
                return ResourceManager.GetString("SceneDetectionThresholdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        public static string SelectFileButtonText {
            get {
                return ResourceManager.GetString("SelectFileButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        public static string SelectFolderButtonText {
            get {
                return ResourceManager.GetString("SelectFolderButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Video Upscale.
        /// </summary>
        public static string SingleVideoUpscaleTabHeader {
            get {
                return ResourceManager.GetString("SingleVideoUpscaleTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upscale.
        /// </summary>
        public static string UpscaleButtonText {
            get {
                return ResourceManager.GetString("UpscaleButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upscale Settings.
        /// </summary>
        public static string UpscaleSettingsHeader {
            get {
                return ResourceManager.GetString("UpscaleSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UpscalingBackendDescription {
            get {
                return ResourceManager.GetString("UpscalingBackendDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upscaling Backend.
        /// </summary>
        public static string UpscalingBackendLabel {
            get {
                return ResourceManager.GetString("UpscalingBackendLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Input and Output.
        /// </summary>
        public static string VideoInputAndOutputHeader {
            get {
                return ResourceManager.GetString("VideoInputAndOutputHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Name.
        /// </summary>
        public static string WorkflowNameLabel {
            get {
                return ResourceManager.GetString("WorkflowNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflows.
        /// </summary>
        public static string WorkflowsLabel {
            get {
                return ResourceManager.GetString("WorkflowsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflows provide convenient access to save and load preset settings for upscaling..
        /// </summary>
        public static string WorkflowsTooltip {
            get {
                return ResourceManager.GetString("WorkflowsTooltip", resourceCulture);
            }
        }
    }
}
